import type { DBShape, Meeting, School } from "./types";

const DEMO_SCHOOL_ID = "demo-trindade";
const DEMO_MEETING_ID = "demo-meeting-trindade";

const school: School = {
  id: DEMO_SCHOOL_ID,
  name: "Autoescola Trindade",
  cnpj: "00.000.000/0001-00",
  owner: "Marcos e Rita Trindade",
  phone: "(48) 3333-0000",
  whatsapp: "(48) 99999-0000",
  instagram: "@autoescolatrindade",
  website: "autoescolatrindade.com.br",
  city: "Florianópolis",
  state: "SC",
  units: 2,
  employees: 14,
  receptionists: 2,
  sales: 1,
  notes: "Conta de demonstração. Todos os dados são fictícios.",
  status: "em_andamento",
  demo: true,
  createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
};

const answers: Meeting["answers"] = {
  meta_contratos: 115,
  contratos_atuais: 105,
  melhor_mes: 121,
  pior_mes: 88,
  faturamento: 315000,
  ticket: 3000,
  lucro_contrato: 900,
  funcionarios: 14,
  atendentes: 3,
  unidades: 2,
  canais: ["Instagram", "Google", "Meta Ads", "Indicação", "Fachada / Passagem"],
  investe_trafego: true,
  investimento: 4500,
  leads_mes: 600,
  leads_ads: 340,
  leads_organico: 180,
  leads_indicacao: 80,
  contratos_trafego: 52,
  sabe_canal: false,
  sabe_campanha: false,
  acompanha_cpl: false,
  acompanha_cac: false,
  ads_fora_horario: true,
  acao_fora_horario: "Fica sem resposta até o dia seguinte",
  leads_dia: 20,
  conversas_simultaneas: 2,
  tempo_resposta: 30,
  quem_responde: "Recepção",
  quem_whatsapp: "Recepção",
  quem_presencial: "Recepção",
  quem_alunos: "Recepção e secretaria",
  quem_instagram: "Sócia",
  quem_fora_horario: "Ninguém",
  msgs_sem_resposta: true,
  leads_sem_resposta: 60,
  frequencia_sem_resposta: "Diariamente",
  recepcao_ocupada: true,
  backup_leads: false,
  horas_repetitivas: 3,
  perguntas_repetidas: "Preço, formas de pagamento, horários, documentos e prazo do processo.",
  perguntas_iniciais: "Nome e se quer primeira habilitação.",
  qualifica_itens: ["Primeira habilitação", "Categoria B"],
  script_padrao: false,
  qualificacao_manual: true,
  fator_decisao: "Preço e proximidade",
  f_leads: 600,
  f_respondidos: 540,
  f_qualificados: 350,
  f_interessados: 210,
  f_visitas: 150,
  f_contratos: 105,
  etapas_monitoradas: ["Lead", "Contrato"],
  convite_visita: true,
  agendamento: true,
  confirmacao: false,
  lembrete: false,
  processo_recepcao: true,
  roteiro_comercial: false,
  processo_fechamento: false,
  equipe_qualifica: false,
  equipe_objecoes: false,
  mede_visita_contrato: false,
  lead_para_responder: "Normalmente ninguém retorna o contato.",
  followup: false,
  acompanha_antigos: false,
  leads_parados: 420,
  quase_fecharam: 60,
  rotina_recuperacao: false,
  ig_seguidores_novos: 320,
  ig_views: 48000,
  ig_mensagens: 140,
  ig_comentarios: 90,
  ig_aborda_novos: false,
  ig_processo_comentarios: false,
  ig_processo_stories: false,
  ig_para_whatsapp: false,
  ig_leads: 60,
  ig_visitas: 18,
  ig_contratos: 11,
  base_existe: true,
  base_total: 2400,
  base_nunca_fecharam: 1900,
  base_pediram_info: 1200,
  base_visitaram: 420,
  base_desistiram: 300,
  base_reativacao: false,
  pos_imediato: "Aluno recebe orientações verbalmente na recepção.",
  pos_automatico: false,
  pos_instrucoes: true,
  pos_lembretes: false,
  pos_acompanhamento: false,
  pos_avaliacao: false,
  pos_indicacao: false,
  pos_recompra: false,
};

export function demoDB(): DBShape {
  const meeting: Meeting = {
    id: DEMO_MEETING_ID,
    schoolId: DEMO_SCHOOL_ID,
    startedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    answers,
    outcome: "pendente",
  };
  return {
    schools: [school],
    meetings: [meeting],
    proposals: [],
    logs: [],
    settings: {
      consultant: "Consultor",
      benchmarkVisitRate: 45,
      benchmarkResponseMinutes: 10,
      recoveryRate: 12,
      reactivationRate: 4,
      hourlyRate: 25,
    },
    session: null,
  };
}

export const DEMO_IDS = { school: DEMO_SCHOOL_ID, meeting: DEMO_MEETING_ID };
